apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vz3iigpku-python
  janus-idp.io/tekton: vz3iigpku-python
  backstage.io/kubernetes-id: vz3iigpku-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vz3iigpku-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
