apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vz3iigpku-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vz3iigpku-python 
  name: vz3iigpku-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vz3iigpku-python 
